apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-alpine
  namespace: simple-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-alpine
  template:
    metadata:
      labels:
        app: simple-alpine
    spec:
      containers:
      - name: simple
        image: demo-simple-alpine
        imagePullPolicy: Never
