# controllerManager:
#   manager:
#     # image:
#     #   tag: "sha-d6af453"
#     env:
#       endpoint: https://tylerflint-qpoint-firebase.serveo.net

injectPodAnnotationsConfigmap:
  annotationsYaml: |-
    qpoint.io/inject-ca: "true"
    qpoint.io/qtap-init-tag: "v0.0.8"
    qpoint.io/qtap-tag: "v0.0.11"
    qpoint.io/qtap-init-egress-port-mapping: "10080:80,10443:443"
    qpoint.io/qtap-init-egress-accept-uids: "1010"
    qpoint.io/qtap-init-egress-accept-gids: "1010"
    qpoint.io/qtap-uid: "1010"
    qpoint.io/qtap-gid: "1010"
    qpoint.io/qtap-log-level: "error"
    qpoint.io/qtap-log-encoding: "console"
    qpoint.io/qtap-log-caller: "false"
    qpoint.io/qtap-egress-http-listen: "0.0.0.0:10080"
    qpoint.io/qtap-egress-https-listen: "0.0.0.0:10443"
    qpoint.io/qtap-status-listen: "0.0.0.0:10001"
    qpoint.io/qtap-block-unknown: "false"
    qpoint.io/qtap-envoy-log-level: "error"
    qpoint.io/qtap-dns-lookup-family: "V4_ONLY"
    qpoint.io/qtap-api-endpoint: "https://api.qpoint.io"
