apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt4
  namespace: gpt4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt4
  template:
    metadata:
      labels:
        app: gpt4
    spec:
      containers:
        - name: gpt4
          image: demo-gpt4:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_URL
              value: "https://api.openai.com/v1/completions"
            - name: API_KEY
              value: "bla"  # Be cautious with API keys in files
            - name: MODEL_NAME
              value: "text-davinci-003"
            - name: TEMPERATURE
              value: "0.5"  # Ensure this is a string if your app expects a string
            - name: MAX_TOKENS
              value: "1024"   # Similarly, ensure this is a string if needed
            - name: REQUESTS_CA_BUNDLE
              value: "/etc/ssl/certs/ca-certificates.crt"
          ports:
            - containerPort: 5000
