global:
  licenseKey: "bla"
  cluster: "demo"
  lowDataMode: true

newrelic-infrastructure:
  privileged: true

kube-state-metrics:
  image:
    tag: "v2.10.0"
  enabled: true

kubeEvents:
  enabled: true

newrelic-prometheus-agent:
  enabled: true
  lowDataMode: true
  config:
    kubernetes:
      integrations_filter:
        enabled: false