apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-ubuntu
  namespace: simple-ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-ubuntu
  template:
    metadata:
      labels:
        app: simple-ubuntu
    spec:
      containers:
      - name: simple
        image: demo-simple-ubuntu
        imagePullPolicy: Never
