version: '3.8'

services:
  curl-geoweather:
    build: curl-geoweather/
    environment:
      - HTTP_PROXY=http://qtap.local:18080
      - HTTPS_PROXY=http://qtap.local:18443
    ports:
      - "4000:80"
    depends_on:
      - qtap.local
  go-geoweather:
    build: go-geoweather/
    environment:
      - HTTP_PROXY=http://qtap.local:18080
      - HTTPS_PROXY=http://qtap.local:18443
    ports:
      - "4001:80"
    depends_on:
      - qtap.local
  php-geoweather:
    build: php-geoweather/
    environment:
      - HTTP_PROXY=http://qtap.local:18080
      - HTTPS_PROXY=http://qtap.local:18443
    ports:
      - "4002:80"
    depends_on:
      - qtap.local
  python-geoweather:
    build: python-geoweather/
    environment:
      - HTTP_PROXY=http://qtap.local:18080
      - HTTPS_PROXY=http://qtap.local:18443
    ports:
      - "4003:80"
    depends_on:
      - qtap.local
  qtap.local:
    image: "qpoint:dev"
    environment:
      - TOKEN=${TOKEN}
    command: >
      proxy
      --envoy-log-level=info
      --log-level=debug
      --registration-token=$TOKEN
      --log-encoding="console"
      --dns-lookup-family="V4_ONLY"
    ports:
      - "10080:10080"
      - "10443:10443"
      - "18080:18080"
      - "18443:18443"
      - "9901:9901"
