apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
  namespace: simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple
        image: demo-simple
        imagePullPolicy: Never
