apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
  namespace: simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        qpoint.io/egress: "enabled"
    spec:
      containers:
      - name: app
        image: demo-simple
        imagePullPolicy: Never
