version: '3.8'

services:
  curl-geoweather:
    build: .
    environment:
      - HTTP_PROXY=http://qtap.local:18080
      - HTTPS_PROXY=http://qtap.local:18443
    depends_on:
      - qtap.local
  qtap.local:
    image: "us-docker.pkg.dev/qpoint-edge/public/qpoint:head"
    environment:
      - TOKEN=${TOKEN}
    command: >
      proxy
      --envoy-log-level=info
      --log-level=debug
      --registration-token=$TOKEN
      --log-encoding="console"
      --dns-lookup-family="V4_ONLY"
    ports:
      - "10001:10001"
      - "10080:10080"
      - "10443:10443"
      - "18080:18080"
      - "18443:18443"
      - "9901:9901"
